# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
t_max: 10050000

runner: "parallel"
batch_size_run: 8

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
agent: "cia"
mac: "basic_mac"
learner: "cia_qmix_learner"
double_q: True
optimizer: 'rmsprop'
mixer: "grad_qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# CIA Loss Coefficient
alpha: 0.02

name: "cia_grad_qmix"
