env: SimpleSpread

env_args:
  map_name: "SimpleSpread"
  n_agents: 3
  local_ratio: 0.5 # weight of local reward
  max_cycles: 2000 # max step of env
  num_env_steps: 2000000
  

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
